config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :people
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :person

  validates :title, :text, presence: true
  # validates :person, absence: true
end

app/models/person.rb
class Person < ApplicationRecord
  self.table_name = 'people'

  validates :name, presence: true
  # validates :name, inclusion: {in: %w(thanh nguyen kaka)} #check in list
  validates :mail, uniqueness: true, on: :create
  validates :mail, presence: true, confirmation: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, message: 'khong dung dinh dang'}
  validates :mail_confirmation, presence: true
  validates :age, numericality: true

  # has_many :articles, inverse_of: :person

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :text, :person_id)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :mail, :age)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :person_id
    = f.number_field :person_id
  .actions = f.submit

app/views/articles/edit.html.slim
h1 Editing article

== render 'form'

= link_to 'Show', @article
'|
= link_to 'Back', articles_path

app/views/articles/index.html.slim
h1 Listing articles

table
  thead
    tr
      th Title
      th Text
      th Person
      th
      th
      th

  tbody
    - @articles.each do |article|
      tr
        td = article.title
        td = article.text
        td = article.person_id
        td = link_to 'Show', article
        td = link_to 'Edit', edit_article_path(article)
        td = link_to 'Destroy', article, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Article', new_article_path

app/views/articles/new.html.slim
h1 New article

== render 'form'

= link_to 'Back', articles_path

app/views/articles/show.html.slim
p#notice = notice

p
  strong Title:
  = @article.title
p
  strong Text:
  = @article.text
p
  strong Person:
  = @article.person_id

= link_to 'Edit', edit_article_path(@article)
'|
= link_to 'Back', articles_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/_form.html.slim
.row
  = form_for person, :html => {:class => 'form-horizontal'} do |f|
    - if person.errors.any?
      #error_explanation
        h2
          = pluralize(person.errors.count, "error")
          |  prohibited this person from being saved:
        ul
          - person.errors.full_messages.each do |message|
            li
              = message
    .form-group
      = f.label :name, 'Name', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :name, class: "form-control"
    .form-group
      = f.label :mail, 'Mail', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :mail, class: "form-control"
    .form-group
      = f.label :mail_confirmation, 'Mail Confirmation', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :mail_confirmation, class: "form-control"
    .form-group
      = f.label :age, 'Age', class: 'control-label col-sm-2'
      .col-sm-10
        = f.number_field :age, class: "form-control"
    .actions
      = f.submit

app/views/people/edit.html.slim
h1
  | Editing Person
= render 'form', person: @person
= link_to 'Show', @person
|  | 
= link_to 'Back', people_path

app/views/people/index.html.slim
p#notice
  = notice
h1
  | People
table
  thead
    tr
      th
        | Name
      th
        | Mail
      th
        | Age
      th[colspan="3"]
  tbody
    - @people.each do |person|
      tr
        td
          = person.name
        td
          = person.mail
        td
          = person.age
        td
          = link_to 'Show', person
        td
          = link_to 'Edit', edit_person_path(person)
        td
          = link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Person', new_person_path

app/views/people/new.html.slim
.well
  | New Person
= render 'form', person: @person
= link_to 'Back', people_path

app/views/people/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @person.name
p
  strong
    | Mail:
  = @person.mail
p
  strong
    | Age:
  = @person.age
= link_to 'Edit', edit_person_path(@person)
|  | 
= link_to 'Back', people_path

app/views/welcome/index.html.erb
<h1>Welcome Ruby</h1>
<p><%= link_to 'People', people_path %></p>
<p><%= link_to 'Articles', articles_path %></p>